AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Rubrik::Polaris::EC2Instance resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: rubrik_polaris_ec2instance.handlers.resource
      Runtime: python3.6
      CodeUri: build/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: rubrik_polaris_ec2instance.handlers.test_entrypoint
      Runtime: python3.6
      CodeUri: build/

